package barrier_options;

import java.io.IOException;

/*
 * 
 * Matthew Lee
 * Spring 2019
 * Practicing Monte Carlo Simulation
 * 
 * 
 * Just a class to try running the various implementations from
 * 
 * 
 * TODO: Check the values generated by your modification (just a multiplication) of the ones generated by the Box-Muller method
 * 		 -Probably doable by generating a few (dozen? hundred?) million floats using this method and tossing them in an array and graphing using some graphics package
 * 
 * 
 * TODO: Write a generic setup function to set up an openCL program
 */

public class Initializer {

	public static void main(String[] args) throws InterruptedException, IOException
	{
		System.out.println("[STATUS] Program Initiated");
		int iterations = 320000000;
		/*System.out.println("======================================================");
		System.out.println("[CPU] Hyperthreaded");
		CPU_approx.threaded(iterations);
		System.out.println("======================================================");
		System.out.println("======================================================");
		System.out.println("======================================================");*/
		System.out.println("[GPU] Accelerated");
		OpenCL_Accelerated.accelerated(iterations);
	}
}
